### ISSUE TITLE
Empty types

### ISSUE THREAD

**Issue by dartess** [miguelmota/keccak256#2]
Hi @miguelmota ! Why are you providing an empty file with types? It looks like the package has types, but it doesn't. I can try to describe the correct types so that no one else feels fooled.

**Comment by miguelmota** [comment]
Package has been converted to TypeScript and typings should be updated now.

Thanks!

Closed by https://github.com/miguelmota/keccak256/commit/ff915ac0c040fd0bfe176a3fff7571c89ac3ae0e
