### ISSUE TITLE
Explicit import Buffer

### ISSUE THREAD

**Issue by dartess** [miguelmota/keccak256#3]
I was unable to use this package with an esbuild because it loses the babel import, which is added implicitly.

It would be nice if the code didn't rely on the global variable, but rather imported the buffer explicitly:

```
const Buffer = require('buffer');
```

I can make PR for this.

**Comment by miguelmota** [comment]
Package has been converted to TypeScript and imports `buffer/Buffer` now. 

Thanks!

Closed by https://github.com/miguelmota/keccak256/commit/febb00cd35442004fd897663d563565bc4871366
